import Head from 'next/head'
import Link from "next/link";
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css';
import WorkIcon from '@mui/icons-material/Work';
import AddIcon from '@mui/icons-material/Add';
import TodoList from './Comp/TodoList';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TODO</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='todo-app'>
      <TodoList />
      
    </div>

    </div>
  )
}
